# Site settings
title: "Jason Lee"
email:
description: > # this means to ignore newlines until "baseurl:"
#baseurl: "/beta/" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username: lee-jason

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-dotenv

# Pagination
paginate: 20
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
