name: Jekyll Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build_and_deploy:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Debug Environment Variables
        run: |
          echo "All environment variables containing AWS:"
          env | grep -i aws || echo "No AWS environment variables found"
          echo "Direct access to AWS_S3_ASSETS_HOST: '$AWS_S3_ASSETS_HOST'"
          echo "GitHub context: ${{ github.ref }}"
      - name: Create .env file
        run: |
          cat > .env << EOF
          AWS_S3_ASSETS_HOST=${{ env.AWS_S3_ASSETS_HOST }}
          EOF
      - name: Debug .env
        run: |
          cat .env
      - name: Build & Push to GitHub Pages
        uses: lee-jason/jekyll4-deploy-gh-pages@master
        with:
          jekyll_config: '_config.yml,_config_prod.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}