name: Jekyll Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Debug Variables
        run: |
          echo "Testing vars access:"
          echo "vars.AWS_S3_ASSETS_HOST: '${{ vars.AWS_S3_ASSETS_HOST }}'"
          echo "Testing env access:"
          echo "env.AWS_S3_ASSETS_HOST: '${{ env.AWS_S3_ASSETS_HOST }}'"
          echo "Testing secrets access:"
          echo "secrets.AWS_S3_ASSETS_HOST: '${{ secrets.AWS_S3_ASSETS_HOST }}'"
      - name: Create .env file
        run: |
          cat > .env << EOF
          AWS_S3_ASSETS_HOST=${{ vars.AWS_S3_ASSETS_HOST }}
          EOF
      - name: Debug .env
        run: |
          cat .env
      - name: Build & Push to GitHub Pages
        uses: lee-jason/jekyll4-deploy-gh-pages@master
        with:
          jekyll_config: '_config.yml,_config_prod.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}